FROM openjdk:17
EXPOSE 8080

COPY . .

#ADD /DrinkmeWebParent/DrinkmeBackEnd/target/isa-project-backend.jar isa-project-backend.jar


#RUN ./DrinkmeWebParent/mvnw clean package

ENTRYPOINT ["java", "-jar", "/DrinkmeBackEnd-0.0.1-SNAPSHOT.jar"]



