version: '3'

services:
  frontend:
    build: ./DrinkmeWebParent/DrinkmeFrontEnd
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/drinkmedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  backend:
    build: ./DrinkmeWebParent/DrinkmeBackEnd
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/drinkmedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

